import type { ReactNode } from "react";
import Link from "next/link";
import { agents, brands, features, plans, problems, steps } from "./landing-data";
import { icons } from "./landing-icons";

function SectionHeading({ eyebrow, children, centered = false }: { eyebrow: string; children: ReactNode; centered?: boolean }) {
  return <div className={`reveal ${centered ? "text-center" : ""}`}><span className="section-tag">{eyebrow}</span><h2 className={`section-title ${centered ? "mx-auto max-w-4xl" : ""}`}>{children}</h2></div>;
}

const Container = ({ children, className = "" }: { children: ReactNode; className?: string }) => <div className={`mx-auto max-w-[1240px] px-5 lg:px-8 ${className}`}>{children}</div>;

export function Logos() { return <section className="border-y border-white/[0.05] bg-[#0A0A0C]"><Container className="flex flex-col items-center gap-7 py-8 lg:flex-row"><span className="whitespace-nowrap text-[10px] uppercase tracking-[0.18em] text-[#444450]">Founders de empresas como →</span><div className="flex flex-1 flex-wrap items-center justify-center gap-x-10 gap-y-4 lg:justify-between">{brands.map((brand) => <span key={brand} className="font-display text-sm font-bold text-[#34343B] transition-colors hover:text-[#686872]">{brand}</span>)}</div></Container></section>; }

export function ProblemSection() { return <section className="section-padding"><Container><SectionHeading eyebrow="Por que founders falham">9 em cada 10 startups fecham.<br /><span className="text-[#555560]">Quase sempre pelo mesmo motivo.</span></SectionHeading><div className="mt-14 grid gap-4 md:grid-cols-3">{problems.map((problem, index) => { const Icon = problem.icon; return <article key={problem.title} className={`reveal delay-${index * 100} premium-card group`}><div className="mb-10 flex h-11 w-11 items-center justify-center rounded-xl border" style={{ color: problem.color, borderColor: `${problem.color}22`, backgroundColor: `${problem.color}09` }}><Icon /></div><h3 className="font-display text-[19px] font-bold leading-tight">{problem.title}</h3><p className="mt-4 text-sm leading-6 text-[#777780]">{problem.description}</p><div className="mt-8 h-px w-10 opacity-40 transition-all duration-500 group-hover:w-20" style={{ backgroundColor: problem.color }} /></article>; })}</div></Container></section>; }

export function SolutionSection() { return <section className="section-padding bg-[#0B0B0D]"><Container><SectionHeading eyebrow="A solução" centered>Seu board executivo de IA,<br /><span className="gradient-text">disponível 24h por dia.</span></SectionHeading><p className="reveal mx-auto mt-6 max-w-2xl text-center text-[15px] leading-7 text-[#777780]">O MetaValley coloca à sua disposição um time de conselheiros de IA com perspectivas reais e conflitantes — e transforma essas conversas em dados concretos de validação de mercado.</p><div className="mt-16 grid gap-4 lg:grid-cols-[1.25fr_0.75fr]"><div className="reveal premium-card relative min-h-[480px] overflow-hidden"><span className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#555560]">Executive Board</span><h3 className="mt-3 max-w-md font-display text-3xl font-bold">Quatro perspectivas reais, em debate.</h3><p className="mt-4 max-w-xl text-sm leading-6 text-[#777780]">CEO quer escalar. CFO questiona o burn. CTO avalia a viabilidade técnica. CMO define o canal. A tensão entre eles é onde o insight real nasce.</p><div className="relative mt-14 grid grid-cols-2 gap-3 sm:grid-cols-4">{agents.map((agent) => <div key={agent.name} className="agent-card" style={{ borderColor: `${agent.color}28` }}><div className="agent-large" style={{ color: agent.color, backgroundColor: `${agent.color}0D` }}>{agent.name[0]}</div><div className="mt-4 text-sm font-semibold">{agent.name}</div><div className="mt-1 text-[10px]" style={{ color: agent.color }}>{agent.role}</div></div>)}</div></div><div className="grid gap-4"><MiniCard title="Canvas Vivo" eyebrow="Live Canvas" tone="green"><div className="mt-5 grid grid-cols-3 gap-1.5 opacity-80">{Array.from({ length: 9 }, (_, index) => <div key={index} className={`h-8 rounded border ${index % 2 ? "border-[#22C55E]/15 bg-[#22C55E]/[0.07]" : "border-white/[0.05] bg-white/[0.018]"}`} />)}</div><p className="mt-5 text-xs leading-5 text-[#777780]">Seu modelo de negócio se constrói sozinho. Cada conversa preenche uma zona do canvas.</p></MiniCard><MiniCard title="Simulação TME" eyebrow="Synthetic Market"><div className="mt-5 flex h-14 items-end gap-1">{[30, 42, 35, 50, 48, 65, 58, 74, 68, 87].map((height) => <div key={height} className="w-full rounded-t bg-[#7F77DD]/30" style={{ height: `${height}%` }} />)}</div><p className="mt-5 text-xs leading-5 text-[#777780]">Simule seu mercado e receba dados de adoção por segmento e projeção de 12 meses.</p></MiniCard></div></div></Container></section>; }

function MiniCard({ eyebrow, title, tone = "purple", children }: { eyebrow: string; title: string; tone?: "purple" | "green"; children: ReactNode }) { return <div className="reveal premium-card min-h-[228px]"><div className="flex items-start justify-between"><div><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#555560]">{eyebrow}</span><h3 className="mt-2 font-display text-xl font-bold">{title}</h3></div><span className={`rounded-lg border px-2 py-1 font-mono text-[8px] uppercase tracking-wider ${tone === "green" ? "border-[#22C55E]/15 text-[#22C55E]" : "border-[#7F77DD]/15 text-[#A19AEF]"}`}>{tone === "green" ? "Auto" : "Em breve"}</span></div>{children}</div>; }

export function HowItWorksSection() { return <section id="como-funciona" className="section-padding"><Container><SectionHeading eyebrow="Em 4 passos">Da ideia à decisão,<br /><span className="text-[#555560]">em minutos.</span></SectionHeading><div className="relative mt-16 grid gap-5 md:grid-cols-4"><div className="timeline-line hidden md:block" />{steps.map(([number, title, description], index) => <div key={number} className={`reveal delay-${index * 100} relative`}><div className="mb-7 flex items-center justify-between md:block"><div className="step-number">{number}</div><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/[0.07] bg-[#111113] text-[#8F89E7] md:mt-5">{icons[["message", "users", "chartDown", "rocket"][index]]({})}</div></div><h3 className="font-display text-[17px] font-bold leading-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-[#6F6F78]">{description}</p></div>)}</div></Container></section>; }

export function FeaturesSection() { return <section id="funcionalidades" className="section-padding bg-[#0B0B0D]"><Container><SectionHeading eyebrow="Funcionalidades">Tudo que você precisa<br /><span className="text-[#555560]">para decidir com inteligência.</span></SectionHeading><div className="mt-14 grid gap-4 md:grid-cols-2">{features.map((feature, index) => { const Icon = feature.icon; return <article key={feature.title} className={`reveal delay-${(index % 4) * 100} feature-card`}><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border" style={{ color: feature.color, backgroundColor: `${feature.color}08`, borderColor: `${feature.color}20` }}><Icon /></div><div><h3 className="font-display text-[18px] font-bold">{feature.title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-[#707078]">{feature.description}</p></div><span className="ml-auto hidden text-[#33333A] sm:block">{icons.arrow({ size: 17 })}</span></article>; })}</div></Container></section>; }

export function TestimonialSection() { return <section className="section-padding"><Container><div className="reveal rounded-3xl border border-white/[0.06] bg-[#111113] px-6 py-14 md:px-14 md:py-20"><div className="mx-auto max-w-4xl text-center"><span className="section-tag">O que os founders dizem</span><blockquote className="mt-9 font-display text-[28px] font-semibold leading-[1.2] text-[#DADAE0] md:text-[40px]">“O MetaValley me fez perceber em 20 minutos que meu modelo de precificação estava completamente errado — antes de eu lançar para o mercado.”</blockquote><div className="mt-8 text-sm text-[#777780]">— Tássia N., Fundadora da Ada Metaverse</div></div><div className="mx-auto mt-14 grid max-w-3xl grid-cols-1 divide-y divide-white/[0.06] border-y border-white/[0.06] sm:grid-cols-3 sm:divide-x sm:divide-y-0">{[["500+", "conversas simuladas"], ["12", "estados"], ["3 meses", "de beta"]].map(([value, label]) => <div key={label} className="px-6 py-6 text-center"><div className="font-display text-2xl font-bold text-[#D4D3DC]">{value}</div><div className="mt-1 text-[10px] uppercase tracking-wider text-[#555560]">{label}</div></div>)}</div></div></Container></section>; }

export function PricingSection() { return <section id="precos" className="section-padding bg-[#0B0B0D]"><div className="mx-auto max-w-[1000px] px-5 lg:px-8"><SectionHeading eyebrow="Planos" centered>Comece de graça.<br /><span className="text-[#555560]">Pague quando fizer sentido.</span></SectionHeading><div className="mt-14 grid gap-4 md:grid-cols-2"><Plan name="Gratuito" eyebrow="Founder" price="R$0" items={plans.free} /><Plan name="Pro" eyebrow="Startup" price="R$79" items={plans.pro} featured /></div><p className="mt-7 text-center text-xs text-[#444450]">Simulação TME disponível como créditos adicionais. Sem contrato. Cancele quando quiser.</p></div></section>; }

function Plan({ name, eyebrow, price, items, featured = false }: { name: string; eyebrow: string; price: string; items: readonly string[]; featured?: boolean }) { return <div className={`reveal ${featured ? "relative overflow-hidden rounded-2xl border border-[#7F77DD]/40 bg-[#16161A] p-7" : "premium-card"}`}><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#7F77DD]">{eyebrow}</span><h3 className="mt-2 font-display text-2xl font-bold">{name}</h3><div className="mt-8 flex items-end gap-2"><span className="font-display text-5xl font-black">{price}</span><span className="mb-2 text-sm text-[#555560]">/mês</span></div><ul className="mt-9 space-y-4">{items.map((item) => <li key={item} className="flex items-center gap-3 text-sm text-[#85858E]"><span className={`h-1.5 w-1.5 rounded-full ${featured ? "bg-[#22C55E]" : "bg-[#555560]"}`} />{item}</li>)}</ul><Link href="/auth/register" className={`${featured ? "primary-button" : "secondary-button"} mt-10 w-full`}>{featured ? "Começar com Pro" : "Começar grátis"}{featured && icons.arrow({ size: 16 })}</Link></div>; }

export function FinalCta() { return <section className="relative overflow-hidden py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(127,119,221,0.13),transparent_48%)]" /><div className="relative mx-auto max-w-[900px] px-5 text-center"><div className="reveal"><span className="section-tag">Comece agora</span><h2 className="mt-6 font-display text-[42px] font-black leading-[1] md:text-[68px]">Sua ideia merece ser testada<br /><span className="gradient-text">antes de ser construída.</span></h2><p className="mx-auto mt-7 max-w-xl text-[15px] leading-7 text-[#777780]">Junte-se a centenas de founders que estão usando dados, não achismos, para decidir o futuro das suas startups.</p><Link href="/auth/register" className="primary-button large-button mx-auto mt-9">Começar gratuitamente {icons.arrow({})}</Link><p className="mt-4 text-[10px] uppercase tracking-[0.14em] text-[#444450]">Sem cartão de crédito · Setup em menos de 2 minutos</p></div></div></section>; }

export function Footer() { return <footer className="border-t border-white/[0.06]"><Container className="py-12"><div className="flex flex-col gap-10 md:flex-row md:items-start md:justify-between"><div><a href="#" className="font-display text-xl font-extrabold text-[#A39DF0]">MetaValley</a><p className="mt-3 text-sm text-[#555560]">Valide antes de construir.</p><p className="mt-8 text-xs text-[#3D3D44]">Desenvolvido em Aracaju, Sergipe</p></div><div className="grid grid-cols-2 gap-x-14 gap-y-4 text-sm text-[#555560] sm:grid-cols-3">{[["Sobre", "#"], ["Como funciona", "#como-funciona"], ["Preços", "#precos"], ["Blog", "#"], ["Termos", "#"], ["Privacidade", "#"]].map(([label, href]) => <a key={label} href={href} className="footer-link">{label}</a>)}</div><div className="flex gap-5 text-sm text-[#555560]"><a href="#" className="footer-link">LinkedIn</a><a href="#" className="footer-link">Instagram</a><a href="#" className="footer-link">X</a></div></div><div className="mt-12 border-t border-white/[0.05] pt-6 text-[10px] uppercase tracking-wider text-[#33333A]">© 2026 MetaValley. Todos os direitos reservados.</div></Container></footer>; }
